version: "3.6"
services:
     db:
         image: postgres:13
         ports:
           - '5435:5432'
         environment:
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=1234
           - POSTGRES_DB=todo